# -*- coding: utf-8 -*-
"""iPhoneComparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pna4HDO0bm6UYtsZz75QKtdmeDQc6u5f
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain-openai==0.2.12
# %pip install streamlit

import os

os.environ["OPENAI_API_KEY"] = st.secret["OPENAI_API_KEY"]

from langchain_openai import ChatOpenAI

gpt4o_mini = ChatOpenAI(model_name = "gpt-4o-mini")

from langchain import PromptTemplate

phone_compare_prompt = "Compare product specificiations in a tabular format between iPhone {model1} and {model2}"
phone_compare_template = PromptTemplate(template = phone_compare_prompt, input_variables =['model1', 'model2'])

from langchain import LLMChain

model_compare_chain = phone_compare_template | gpt4o_mini

import streamlit as st

st.header("Compare different iPhone models")
st.subheader("Select from a list of iPhone models from dropdown to compare their product specifications")
pmodel1 = st.selectbox('Select first model',('iPhone 11', 'iPhone 12', 'iPhone 13', 'iPhone 14'))
pmodel2 = st.selectbox('Select second model',('iPhone 11', 'iPhone 12', 'iPhone 13', 'iPhone 14'))
if st.button("Compare"):
  compare=model_compare_chain.invoke({'pmodel1','pmodel2'})
  st.write(compare.content)
