# -*- coding: utf-8 -*-
"""iPhoneComparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pna4HDO0bm6UYtsZz75QKtdmeDQc6u5f
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain-openai==0.2.12
# %pip install streamlit
from langchain_openai import ChatOpenAI
from langchain import PromptTemplate
from langchain import LLMChain
import os
import streamlit as st

os.environ['OPENAI_API_KEY'] = st.secrets['OPENAI_API_KEY']

gpt4o_mini = ChatOpenAI(model_name = "gpt-4o-mini")

phone_compare_prompt = "Compare product specificiations in a tabular format between iPhone {model1} and {model2}"
phone_compare_template = PromptTemplate(template = phone_compare_prompt, input_variables =['model1', 'model2'])

model_compare_chain = phone_compare_template | gpt4o_mini

st.header("Compare different iPhone models")
st.subheader("Select from a list of iPhone models to compare their product specifications")
pmodel1 = st.selectbox('Select first model',('iPhone 11', 'iPhone 12', 'iPhone 12 Pro', 'iPhone 12 Pro max', 'iPhone 13', 'iPhone 13 Pro', 'iPhone 13 Pro Max'))
pmodel2 = st.selectbox('Select second model',('iPhone 11', 'iPhone 12', 'iPhone 12 Pro', 'iPhone 12 Pro max', 'iPhone 13', 'iPhone 13 Pro', 'iPhone 13 Pro Max'))
if st.button("Compare"):
  compare=model_compare_chain.invoke({"model1": pmodel1,"model2": pmodel2})
  st.write(compare.content)
