# -*- coding: utf-8 -*-
"""iPhoneComparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pna4HDO0bm6UYtsZz75QKtdmeDQc6u5f
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain-openai==0.2.12

import os

os.environ["OPENAI_API_KEY"] = ""

from langchain_openai import ChatOpenAI

gpt4o_mini = ChatOpenAI(model_name = "gpt-4o-mini")

from langchain import PromptTemplate

phone_compare_prompt = "Compare product specificiations in a tabular format between iPhone {model1} and {model2}"
phone_compare_template = PromptTemplate(template = phone_compare_prompt, input_variables =['model1', 'model2'])

from langchain import LLMChain

model_compare_chain = phone_compare_template | gpt4o_mini

response = model_compare_chain.invoke({"model1" : "iPhone 11", "model2" : "iPhone 14"})
print(response.content)